spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    root: INFO
    com.tripperr.api: INFO
    org.springframework.security: WARN

management:
  endpoint:
    health:
      show-details: when_authorized
