spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  error:
    include-message: never

logging:
  level:
    root: WARN
    com.tripperr.api: INFO

management:
  endpoint:
    health:
      show-details: never
